version: '3.8'

services:


  db-Despachos:
    build: ./BD/BD-Despachos
    container_name: back-despachos_springboot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_Despachos
    ports:
      - "3307:3306"
    volumes:
      - inventario_data:/var/lib/mysql
    networks:
      - red_interna
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -padmin123 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  db-ventas:
    build: ./BD/BD-Ventas
    container_name: back-ventas_springboot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_Ventas
    ports:
      - "3308:3306"
    volumes:
      - ventas_data:/var/lib/mysql
    networks:
      - red_interna
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -padmin123 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Backend Ventas (IE6)
  back-ventas:
    build: ./back-ventas_springboot
    container_name: backend_ventas
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/base_datos_app
      SPRING_DATASOURCE_USERNAME: user_devops
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - db
    networks:
      - red_interna

  # Backend Despachos (IE6)
  back-despachos:
    build: ./back-despachos_springboot
    container_name: backend_despachos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/base_datos_app
      SPRING_DATASOURCE_USERNAME: user_devops
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - db
    networks:
      - red_interna

  # Frontend (IE5)
  frontend:
    build: ./FRONT_DESPACHO
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge

volumes:
  db_data: