services:
  DB-Despachos:
    build:
      context: ./BD/BD-Despachos
      dockerfile: Dockerfile.prod
    container_name: back-despachos_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_Despachos
    ports:
      - "3307:3306"
    volumes:
      - inventario_data:/var/lib/mysql
    networks:
      - red_interna

  DB-Ventas:
    build:
      context: ./BD/BD-Ventas
      dockerfile: Dockerfile.prod
    container_name: back-ventas_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_Ventas
    ports:
      - "3308:3306"
    volumes:
      - ventas_data:/var/lib/mysql
    networks:
      - red_interna

volumes:
  despacho_data:
  ventas_data:

networks:
  red-tienda:
    driver: bridge
